/**
 * 打开Native方法
 * @authors (移动新媒体事业部)
 * @date    2015-01-04 17:12:36
 * @version $Id$
 */

var $ = require('zepto');
var UI = require('./core');

var openNative = (function () {

  // Helpers

  var toString = Object.prototype.toString;
  var hasOwnProperty = Object.prototype.hasOwnProperty;
  var isArray = Array.isArray || function (val) {
      return toString.call(val) === '[object Array]';
    };
  var trim = String.prototype.trim ?
    function (str) {
      return (str == null) ?
        '' :
        String.prototype.trim.call(str);
    } :
    function (str) {
      return (str == null) ?
        '' :
        str.toString().replace(/^\s+/, '').replace(/\s+$/, '');
    };

  /**
   * Deserialize a query string to an object. Optionally override the default
   * separator and assignment characters.
   *
   * parse('a=b&c=d')
   *   // returns {a: 'b', c: 'c'}
   */
  var parseURL = function (str, sep, eq) {
    var ret = {};

    if (typeof str !== 'string' || trim(str).length === 0) {
      return ret;
    }

    var pairs = str.split(sep || '&');
    eq = eq || '=';
    var unescape = function (s) {
      // The + character is interpreted as a space on the server side as well as
      // generated by forms with spaces in their fields.
      return decodeURIComponent(s.replace(/\+/g, ' '));
    };

    for (var i = 0; i < pairs.length; i++) {

      var pair = pairs[i].split(eq);
      var key = unescape(trim(pair[0]));
      var val = unescape(trim(pair.slice(1).join(eq)));

      var m = key.match(/^(\w+)\[\]$/);
      if (m && m[1]) {
        key = m[1];
      }

      if (hasOwnProperty.call(ret, key)) {
        if (!isArray(ret[key])) {
          ret[key] = [ret[key]];
        }
        ret[key].push(val);
      } else {
        ret[key] = m ? [val] : val;
      }
    }

    return ret;
  };

  // 创建一个 iframe 丢到页面中，加载某条链接
  function loadIframe(url) {
    var timer = null;

    var iframe = document.createElement('iframe');
    iframe.style.display = 'none';
    iframe.src = url;

    var callback = function () {
      if (iframe && iframe.readyState && iframe.readyState != 'loaded' && iframe.readyState != 'complete') {
        return;
      }

      // 清理 iframe 标签
      iframe.onload = iframe.onreadystatechange = iframe.onerror = null;
      iframe.src = '';
      iframe.parentNode.removeChild(iframe);
      iframe = null;

      if (timer) {
        clearTimeout(timer);
        timer = null;
      }

      //window.location.href = 'http://3g.k.sohu.com';
    };

    iframe.onload = iframe.onerror = iframe.onreadystatechange = callback;
    document.getElementsByTagName('body')[0].appendChild(iframe);

    timer = setTimeout(function () {
      callback();
    }, 40);
  }

  function getQueryString(name) {
    var reg = new RegExp('(^|&)' + name + '=([^&]*)(&|$)', 'i');
    var r = window.location.search.substr(1).match(reg);
    if (r != null) return unescape(r[2]);
    return null;
  }

  /**
   * 呼起Native
   * @param  {String}  shareLink 呼起客户端的对应页面的二代协议（不含'sohunewsiphone://pr/'），如果不传则只呼起客户端
   * @param  {Boolean} pageLoad true:表示进入页面触发打开native方法，
   *                            false:表示进入页面不触发打开native操作
   在微信和微博中不执行呼起客户端操作）
   */
  function _openNative(jsonStr, shareLink, pageLoad) {
    jsonStr = jsonStr || '';
    pageLoad = !!pageLoad;
    shareLink = shareLink || '';

    switch (shareLink) {
      case 'http://3g.k.sohu.com':
      case 'http://3g.k.sohu.com/':
      case '3g.k.sohu.com':
      case '3g.k.sohu.com/':
        shareLink = '';
    }

    var ua = navigator.userAgent;
    // 新浪微博
    var weiboUA = ua.match(/__weibo__([\d.]+)/),
    // 微信
      weixinUA = ua.match(/MicroMessenger\/([\d.]+)/),
      iosUA = ua.match(/(iPhone|iPad|iPod|iOS)/i),
      isMobile = !!ua.match(/(iPhone|iPad|iPod|iOS|android)/i),
      isCooperation = false,
      isSohuNewsApp = false;

    // 合作方新闻页面不唤醒客户端 央视，灵犀，豌豆荚内引用的新闻页面，均不唤醒搜狐新闻
    var referSite = getQueryString('referSite');
    switch (referSite) {
      case 'yangshi':
      case 'lingxi':
      case 'wandoujia':
      case 'sns_h5':
        isCooperation = true;
    }

    if (ua.match(/SohuNews\/([\d.]+)/)) {
      isSohuNewsApp = true;
    }

    // 完整的呼起客户端链接
    var openLink = 'http://3g.k.sohu.com';
    var scheme = iosUA ? 'sohunewsiphone' : 'sohunews';
    var appProtocolLink = '';
    // if(!!shareLink){
    //     appProtocolLink = scheme + '://pr/' + shareLink+'&refer=h5&refererUrl='+encodeURIComponent(window.location.href);
    // }else{
    //     appProtocolLink = scheme + '://pr/' + shareLink;
    // }
    // if(iosUA){
    //     appProtocolLink = scheme + '://pr/' + shareLink;
    // }else{
    appProtocolLink = scheme + '://pr/' + encodeURIComponent(shareLink) + '?' + jsonStr;
    // }
    var isappinstalled = _getIsAppInstalled();

    if (weiboUA) {
      openLink = 'http://3g.k.sohu.com/qr/jump.jsp?link=' + appProtocolLink + '&isappinstalled=' + isappinstalled + '&referSite=sinaweibo';
    } /*else if (weixinUA) {
     openLink = 'http://a.app.qq.com/o/simple.jsp?pkgname=com.sohu.newsclient&g_f=9917';
     } */ else {
      openLink = 'http://3g.k.sohu.com';
    }

    if (isSohuNewsApp) {
      return;
    }

    if (pageLoad) {
      if (!weixinUA && isMobile && !isCooperation && !isSohuNewsApp) {
        loadIframe(appProtocolLink); // remove after 40ms
      }
    } else {
      loadIframe(appProtocolLink); // remove after 40ms
    }
  }

  function _getIsAppInstalled() {
    var params = parseURL(location.search.replace(/^\?/, ''));
    var isappinstalled = params['isappinstalled'] || 0;
    return isappinstalled;
  }

  return {
    open: _openNative,
    getIsAppInstalled: _getIsAppInstalled
  };

}());

UI.openNative = openNative;
module.exports = openNative;
// $SohuNewsScope.openNative.open();