/**
 * 点击调起客户端
 */

var openNative = (function () {

  // Helpers
  var toString = Object.prototype.toString;
  var hasOwnProperty = Object.prototype.hasOwnProperty;
  var isArray = Array.isArray || function (val) {
      return toString.call(val) === '[object Array]';
    };
  var trim = String.prototype.trim ?
    function (str) {
      return (str == null) ?
        '' :
        String.prototype.trim.call(str);
    } :
    function (str) {
      return (str == null) ?
        '' :
        str.toString().replace(/^\s+/, '').replace(/\s+$/, '');
    };

  /**
   * Deserialize a query string to an object. Optionally override the default
   * separator and assignment characters.
   *
   * parse('a=b&c=d')
   *   // returns {a: 'b', c: 'c'}
   */
  var parseURL = function (str, sep, eq) {
    var ret = {};

    if (typeof str !== 'string' || trim(str).length === 0) {
      return ret;
    }

    var pairs = str.split(sep || '&');
    eq = eq || '=';
    var unescape = function (s) {
      // The + character is interpreted as a space on the server side as well as
      // generated by forms with spaces in their fields.
      return decodeURIComponent(s.replace(/\+/g, ' '));
    };

    for (var i = 0; i < pairs.length; i++) {

      var pair = pairs[i].split(eq);
      var key = unescape(trim(pair[0]));
      var val = unescape(trim(pair.slice(1).join(eq)));

      var m = key.match(/^(\w+)\[\]$/);
      if (m && m[1]) {
        key = m[1];
      }

      if (hasOwnProperty.call(ret, key)) {
        if (!isArray(ret[key])) {
          ret[key] = [ret[key]];
        }
        ret[key].push(val);
      } else {
        ret[key] = m ? [val] : val;
      }
    }

    return ret;
  };

  // 创建一个iframe丢到页面中，加载某条链接
  function loadIframe(url) {

    var timer = null;

    var iframe = document.createElement('iframe');
    iframe.style.display = 'none';

    iframe.src = url;

    var callback = function () {

      if (iframe && iframe.readyState && iframe.readyState != "loaded" && iframe.readyState != "complete") {
        return;
      }
      // 清理iframe标签
      iframe.onload = iframe.onreadystatechange = iframe.onerror = null;
      iframe.src = "";
      iframe.parentNode.removeChild(iframe);
      iframe = null;

      if (timer) {
        clearTimeout(timer);
        timer = null;
      }
    };

    iframe.onload = iframe.onerror = iframe.onreadystatechange = callback;
    document.getElementsByTagName("body")[0].appendChild(iframe);

    timer = setTimeout(function () {
      callback();
    }, 40);
  }

  function getQueryString(name) {
    var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)", "i");
    var r = window.location.search.substr(1).match(reg);
    if (r != null) return unescape(r[2]);
    return null;
  }

  /**
   * 呼起Native
   * @param  {String}  shareLink 呼起客户端的对应页面的二代协议（不含'sohunewsiphone://pr/'），如果不传则只呼起客户端
   * @param  {Boolean} pageLoad true:表示进入页面触发打开native方法，
   *                            false:表示进入页面不触发打开native操作
   在微信和微博中不执行呼起客户端操作）
   * @param  {Boolean} isBackflowPage true: ios9以上直接唤起客户端，微信QQ微博弹出浮层，其他情况也直接唤起客户端，
   */
  function _openNative(jsonStr, shareLink, pageLoad, isBackflowPage) {
    jsonStr = jsonStr || '';
    pageLoad = !!pageLoad;
    shareLink = shareLink || '';
    switch (shareLink) {
      case 'http://3g.k.sohu.com':
      case 'http://3g.k.sohu.com/':
      case '3g.k.sohu.com':
      case '3g.k.sohu.com/':
        shareLink = '';
    }

    var ua = navigator.userAgent;
    // 新浪微博
    var weiboUA = ua.match(/__weibo__([\d.]+)/),
    // 微信
      weixinUA = ua.match(/MicroMessenger\/([\d.]+)/),
      iosUA = ua.match(/(iPhone|iPad|iPod|iOS)/i),
      androidUA = ua.match(/Android/i),
      isMobile = !!ua.match(/(iPhone|iPad|iPod|iOS|android)/i),
      isCooperation = false,
      isSohuNewsApp = false;

    // 合作方新闻页面不唤醒客户端 央视，灵犀，豌豆荚内引用的新闻页面，均不唤醒搜狐新闻
    var referSite = getQueryString("referSite");
    switch (referSite) {
      case 'yangshi':
      case 'lingxi':
      case 'wandoujia':
      case 'sns_h5':
        isCooperation = true;
    }

    if (ua.match(/SohuNews\/([\d.]+)/)) {
      isSohuNewsApp = true;
    }

    // 完整的呼起客户端链接
    var openLink = "http://3g.k.sohu.com";
    var scheme = iosUA ? 'sohunewsiphone' : 'sohunews';
    var appProtocolLink = '';

    // if(!!shareLink){
    //     appProtocolLink = scheme + '://pr/' + shareLink+'&refer=h5&refererUrl='+encodeURIComponent(window.location.href);
    // }else{
    //     appProtocolLink = scheme + '://pr/' + shareLink;
    // }
    // if(iosUA){
    //     appProtocolLink = scheme + '://pr/' + shareLink;
    // }else{
    appProtocolLink = scheme + '://pr/' + encodeURIComponent(shareLink) + '?' + jsonStr;
    // }
    var isappinstalled = _getIsAppInstalled();

    //if (weiboUA) {
    //openLink = "http://3g.k.sohu.com/qr/jump.jsp?link=" + appProtocolLink + "&isappinstalled=" + isappinstalled + "&referSite=sinaweibo";
    // } else if (weixinUA) {
    //     openLink = "http://a.app.qq.com/o/simple.jsp?pkgname=com.sohu.newsclient&g_f=9917";
    // } else {
    //     openLink = 'http://3g.k.sohu.com';
    //}
//------端内跳转
    if (isSohuNewsApp) {
      return;
    }
    if (pageLoad) {
      if (!weixinUA && isMobile && !isCooperation && !isSohuNewsApp) {
        if (!!iosUA) {
          loadIframe(appProtocolLink); // remove after 40ms
          setTimeout(function () {
            window.location.href = appProtocolLink;
          }, 50);
        } else if (!!androidUA) {
          loadIframe(appProtocolLink);
        }


        /*try{//可能抛出异常的代码
         loadIframe(appProtocolLink); // remove after 40ms
         setTimeout(function() {
         window.location.href=appProtocolLink;
         }, 50);
         }catch(error){//如果发生异常会执行的代码，error为发生的异常类对象
         window.location.reload();
         }*/
      }
    }
//---------端内end
    else if (isBackflowPage === true) {
      // debugger
      (function () {
        //alert(navigator.userAgent)
        var isIos = navigator.userAgent.match(/(iPhone|iPad|iPod|iOS)/i);
        var isAndroid = navigator.userAgent.match(/Android/i);

        function isWeiXin() {
          if (navigator.userAgent.match(/MicroMessenger/i) == 'micromessenger' || navigator.userAgent.indexOf('MicroMessenger') !== -1) {
            return true;
          } else {
            return false;
          }
        }

        var originUa = navigator.userAgent;

        function getRefer() {
          var ref = "other";
          if (/SohuNews/i.test(originUa)) {
            ref = "sohunews";
          } else if (/MicroMessenger/i.test(originUa)) {
            ref = "weixin";
          } else if (/weibo/i.test(originUa)) {
            ref = "weibo";
          } else if (/Qzone/i.test(originUa)) {
            ref = "Qzone";
          } else if (originUa.indexOf('Mobile MQQBrowser') !== -1 || originUa.indexOf('QQ') !== -1) { // android ios
            ref = "QQ";
          } else if (/MQQBrowser/i.test(originUa)) {
            ref = "qqbrowser";
          } else if (/CriOS/i.test(originUa) || /Chrome/i.test(originUa)) {
            ref = "chrome";
          } else if (/UCBrowser/i.test(originUa) || /UCWEB/i.test(originUa)) {
            ref = "UC";
          } else if (/FlyFlow/i.test(originUa)) {
            ref = "baidu";
          } else if (/Mercury/i.test(originUa)) {
            ref = "Mercury";
          } else if (/SogouMobileBrowser/i.test(originUa)) {
            ref = "sogou";
          } else if (/Opera/i.test(originUa)) {
            ref = "opera";
          } else if (/baiduboxapp/i.test(originUa)) {
            ref = "baidubox";
          } else if (/hao123/i.test(originUa)) {
            ref = "hao123";
          }
          return ref;
        }

        var originStr = getRefer();
        //alert(originStr);
        // ios9.3以上直接唤起
        //alert(navigator.userAgent.indexOf('OS 9_') !== -1 && navigator.userAgent.indexOf('OS 9_1') === -1 && navigator.userAgent.indexOf('OS 9_2') === -1)
        //alert(navigator.userAgent)
        /*if (navigator.userAgent.indexOf('OS 9_') !== -1 && navigator.userAgent.indexOf('OS 9_1') === -1 && navigator.userAgent.indexOf('OS 9_2') === -1) {
         location.href = 'https://api.k.sohu.com?url='+shareLink;
         setTimeout(function(){
         location.href = 'http://3g.k.sohu.com/';
         }, 50);
         }else */
        if (isWeiXin() || originStr == "QQ" || originStr == "weibo") {
          //alert('weixin qq weibo')
          var imgUrl = '';
          if (isIos) {
            imgUrl = 'http://k.sohu.com/static/live/img/share_ios.png';
          } else if (isAndroid) {
            imgUrl = 'http://k.sohu.com/static/live/img/share_android.png';
          } else {
            location.href = openLink;
            return;
          }
          var html =
              '<div id="g-backflow" style="position: fixed;top: 0;left: 0;right: 0;width: 100%;height: 100%;background-color: #fff;z-index: 10000;">' +
              '<div>' +
              '<img class="iguide" style="width: 100%" src="' + imgUrl + '">' +
              '</div>' +
              '</div>'
            ;
          $('body').append(html);
        } else {
          loadIframe(appProtocolLink); // remove after 40ms
          window.location = appProtocolLink;
          setTimeout(function () {
            window.location.href = openLink;
          }, 3000);
        }
      })();
    }
    else {
      if (iosUA) {
        if (!!weixinUA) {
          window.location.href = 'http://a.app.qq.com/o/simple.jsp?pkgname=com.sohu.newsclient&g_f=991701';
        } else {
          loadIframe(appProtocolLink); // remove after 40ms
          setTimeout(function () {
            window.location.href = openLink;
          }, 49);
          setTimeout(function () {
            window.location.href = appProtocolLink;
          }, 50);
        }
      } else if (androidUA) {
        if (!!weixinUA) {
          window.location.href = 'http://a.app.qq.com/o/simple.jsp?pkgname=com.sohu.newsclient&g_f=991701';
        } else {
          loadIframe(appProtocolLink); // remove after 40ms
          setTimeout(function () {
            window.location.href = openLink;
          }, 50);

        }
      } else {//-----------含pc
        loadIframe(appProtocolLink); // remove after 40ms
        setTimeout(function () {
          window.location.href = openLink;
        }, 50);
      }
    }
  }

  function _getIsAppInstalled() {
    var params = parseURL(location.search.replace(/^\?/, ''));
    var isappinstalled = params['isappinstalled'] || 0;
    return isappinstalled;
  }

  return {
    open: _openNative,
    getIsAppInstalled: _getIsAppInstalled
  };

}());

module.exports = openNative;
